# config-repo/api-gateway.yml
server:
  port: 8080

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      # Keep your real routes here
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**,/users/**
          filters:
            - StripPrefix=1

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**,/inventory/**
          filters:
            - StripPrefix=1

        - id: qr-service
          uri: lb://qr-service
          predicates:
            - Path=/api/qr/**,/qr/**
          filters:
            - StripPrefix=1

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**,/auth/**
          filters:
            - StripPrefix=1
