# config-repo/qr-service.yml
server:
  port: 8093

spring:
  application:
    name: qr-service

  cloud:
    stream:
      bindings:
        qrGenerated-out-0:
          destination: qr-generated-events
          content-type: application/json
        qrDecoded-out-0:
          destination: qr-decoded-events
          content-type: application/json
