server:
  port: 8761

spring:
  application:
    name: service-registry

eureka:
  client:
    # The registry itself does NOT need to register with another Eureka
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:
    # Make the UI refresh a bit faster in dev
    wait-time-in-ms-when-sync-empty: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
