# config-repo/service-registry.yml
spring:
  application:
    name: service-registry
  cloud:
    config:
          enabled: false

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0

