# config-repo/user-service.yml
server:
  port: 8091

spring:
  application:
    name: user-service

  # Optional override (only if you really want it different from global):
  # jpa:
  #   hibernate:
  #     ddl-auto: create-drop
