# config-repo/user-service.yml
server:
  port: 8091

spring:
  application:
    name: user-service

security:
  shared:
    permit-all:
      - "/api/users" # Method: POST is implicitly allowed if we don't specify
