version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/maybank_db
      - DB_USERNAME=maybank
      - DB_PASSWORD=maybank
      - JWT_SECRET=dev-secret-key
      - SPRING_REDIS_HOST=redis
    depends_on:
      - db
      - redis
    networks:
      - backend-network

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=maybank_db
      - POSTGRES_USER=maybank
      - POSTGRES_PASSWORD=maybank
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend-network

volumes:
  postgres-data:
  redis-data:

networks:
  backend-network:
    driver: bridge